# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingpoint',
            name='id_url',
            field=models.URLField(default='', unique=True),
            preserve_default=False,
        ),
    ]
