# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_samplingpoint_id_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Determinand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_url', models.URLField(unique=True)),
                ('label', models.CharField(max_length=255)),
                ('notation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_url', models.URLField(unique=True)),
                ('result', models.FloatField()),
                ('determinand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mapping.Determinand')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_url', models.URLField(unique=True)),
                ('date_time', models.DateTimeField()),
                ('sampling_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='mapping.SamplingPoint')),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='mapping.Sample'),
        ),
    ]
