# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_auto_20161015_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
